# fly.toml app configuration file generated for aegisforge on 2026-05-06T00:20:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aegisforge'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
